### ISSUE TITLE
Build fails on TS3.9+

### ISSUE THREAD

**Issue by 0kku** [0kku/destiny#1]
Building project fails on TypeScript 3.9 and up. Culprit is [ReactiveArray#flat()](https://github.com/0kku/destiny/blob/c1777a08ec9d34bc1e985ca04c0cff1ebf8783ff/src/Destiny/reactive/ReactiveArray.ts#L396). 

Workaround (courtesy of @b-fuze): 
```ts
    const newArr = new this.species(...this.#value.flat(<1> <unknown> depth));
    this.#callbacks.add(() => {
      newArr.value = this.#value.flat(<1> <unknown> depth);
    });
```
Let's keep using 3.8 for now, but resort to using the workaround if we need features from newer versions of TS before the compiler bug is fixed.

Depends on https://github.com/microsoft/TypeScript/issues/38298

**Comment by b-fuze** [comment]
LGTM, merged 😄

**Comment by 0kku** [comment]
I was looking over the method, and realized `ReactiveArray::flat()` was poorly implemented, and decided to remove it entirely for now. So, upgrading to a newer version of TS should be fine now. I'll implement the method (properly this time) once the compiler bug is resolved. 

The issue with the old implementation was, that it didn't take into account that nested arrays are now implicitly made reactive recursively, which wasn't the case when it was first implemented (who would've thought that writing some tests for this lib might be useful? 🤦‍♂️). This change means that implementing `ReactiveArray::flat()` and `ReactiveArray::flatMap()` might be  a little tricky. But I won't investigate it until MS fixes their compiler.
